
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami6
  # namespace: whoami6
  labels:
    allow.http: "false"
    application: whoami6
spec:
  replicas: 3
  selector:
    matchLabels:
      application: whoami6
  template:
    metadata:
      labels:
        application: whoami6
    spec:
      containers:
      - name: whoami6
        image: jwilder/whoami
        ports:
        - containerPort: 7000
        securityContext:
          privileged: true


---
apiVersion: v1
kind: Service
metadata:
  name: whoami6
  annotations: 
    traefik.ingress.kubernetes.io/service.sticky: "true"
  # namespace: whoami6
spec:
  type: ClusterIP
  ports:
  - port: 80 # Porta a ser exposta pelo SERVICE
    targetPort: 8000 # Porta que a aplicação está rodando no POD
  selector:
    application: whoami6

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: whoami6
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
    # traefik.ingress.kubernetes.io/router.tls.certresolver: default
spec:
  rules:
    - host: app6.staging.sti.ufpb.br
      http:
        paths:
          - backend:
              serviceName: whoami6
              servicePort: 80

