
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami7
  namespace: staging
  labels:
    allow.http: "false"
    application: whoami7
spec:
  replicas: 3
  selector:
    matchLabels:
      application: whoami7
  template:
    metadata:
      labels:
        application: whoami7
    spec:
      containers:
      - name: whoami7
        image: jwilder/whoami
        ports:
        - containerPort: 7000
        securityContext:
          privileged: true


---
apiVersion: v1
kind: Service
metadata:
  name: whoami7
  annotations: 
    traefik.ingress.kubernetes.io/service.sticky: "true"
  namespace: staging
spec:
  type: ClusterIP
  ports:
  - port: 80 # Porta a ser exposta pelo SERVICE
    targetPort: 8000 # Porta que a aplicação está rodando no POD
  selector:
    application: whoami7

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: whoami7
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
spec:
  tls:
    - hosts:
        - app7.staging.sti.ufpb.br
      secretName: staging-tls-secret
  rules:
    - host: app7.staging.sti.ufpb.br
      http:
        paths:
          - backend:
              serviceName: whoami7
              servicePort: 80

