
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami-middleware
  namespace: staging
  labels:
    allow.http: "false"
    application: whoami-middleware
spec:
  replicas: 3
  selector:
    matchLabels:
      application: whoami-middleware
  template:
    metadata:
      labels:
        application: whoami-middleware
    spec:
      containers:
      - name: whoami-middleware
        image: jwilder/whoami
        ports:
        - containerPort: 7000
        securityContext:
          privileged: true

---
apiVersion: v1
kind: Service
metadata:
  name: whoami-middleware
  annotations: 
    traefik.ingress.kubernetes.io/service.sticky: "true"
  namespace: staging
spec:
  type: ClusterIP
  ports:
  - port: 80 # Porta a ser exposta pelo SERVICE
    targetPort: 8000 # Porta que a aplicação está rodando no POD
  selector:
    application: whoami-middleware

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-http
  namespace: staging
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: "443"

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: https-whoami-middleware
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - app-middleware.staging.sti.ufpb.br
      secretName: staging-tls-secret
  rules:
    - host: app-middleware.staging.sti.ufpb.br
      http:
        paths:
          - backend:
              service:
                name: whoami-middleware
                port:
                  number: 80
            path: /
            pathType: Prefix

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: http-whoami-middleware
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web    
    traefik.ingress.kubernetes.io/router.middlewares: staging-redirect-http@kubernetescrd # concat NAMESPACE with name of middleware
spec:
  rules:
    - host: app-middleware.staging.sti.ufpb.br
      http:
        paths:
          - backend:
              service:
                name: whoami-middleware
                port:
                  number: 80
            path: /
            pathType: Prefix